# Generated by Django 4.2.10 on 2024-02-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("education", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C", "C"),
                            ("C++", "C++"),
                            ("Java", "Java"),
                            ("Python", "Python"),
                            ("JavaScript", "JavaScript"),
                            ("React", "React"),
                            ("R", "R"),
                            ("Haskell", "Haskell"),
                            ("SQL", "SQL"),
                            ("HTML_CSS", "HTML and CSS"),
                            ("PHP", "PHP"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "interests",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Development", "Development"),
                            ("AI_ML", "Artificial Intelligence and Machine Learning"),
                            ("DBA", "DBA (Database Administrator)"),
                            ("Testing_Automation", "Testing and Automation"),
                            ("Research", "Research Field"),
                            ("UI_UX", "UI/UX Designer"),
                            ("Cyber_Security", "Cyber Security Engineer"),
                            ("IoT", "Internet of Things (IOT)"),
                            ("Data_Mining", "Data Mining"),
                            ("Data_Science", "Data Science"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("university", models.CharField(max_length=100)),
            ],
        ),
    ]
