# Generated by Django 4.2.10 on 2024-02-18 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aitool", "0002_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="default@example.com",
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Email must be a valid Gmail or Yahoo address.",
                        regex="^[a-zA-Z0-9_.+-]+@(gmail\\.com|yahoo\\.com)$",
                    )
                ],
            ),
        ),
    ]
